### ISSUE TITLE
potential - add unmaintained label

### ISSUE THREAD

**Issue by lb-** [wagtail-nest/wagtail-hallo#18]
Once Wagtail 3.0 is out and this package is updated, we may want to flag with a badge that it is unmaintained.

Saw this in the wild - might come in handy
http://unmaintained.tech/

Or. 
https://img.shields.io/maintenance/no/2022

**Comment by lb-** [comment]
Update - moved to Wagtail Nest organisation so that there are opportunities for others in the community to contribute.

**Comment by allcaps** [comment]
We'd also move this package to https://github.com/wagtail-nest-deprecated

**Comment by lb-** [comment]
I'll close this for now. If we find that this does not get community contributions we can revisit moving this to deprecated.
